### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [Kylsha/easyPlugin#1]
Please adjust metadata.txt to reference a working link for the plugin

**Comment by pavelpereverzev** [comment]
@NyakudyaA hello! I have checked, each link in metadata is working. The only homepage is still under development. What is missed?

**Comment by pavelpereverzev** [comment]
> Please adjust metadata.txt to reference a working link for the plugin

@NyakudyaA I have checked another latest plugins, some have issue tracker with repo_link+issues, some other have just repo_link. Mine has [https://github.com/Kylsha/easyPlugin/issues](https://github.com/Kylsha/easyPlugin/issues) which looks like ok. Or there's something else to be corrected?

**Comment by NyakudyaA** [comment]
Please change the link, it currently shows
<img width="1320" alt="Screenshot 2024-03-13 at 09 23 46" src="https://github.com/Kylsha/easyPlugin/assets/2510900/9ccb4572-ca52-4626-bcb7-b3db62241f34">

Which is unacceptable. If you do not have a proper link please use https://github.com/Kylsha/easyPlugin as the plugin homepage link

**Comment by pavelpereverzev** [comment]
@NyakudyaA Done. Both in https://plugins.qgis.org/ and here in metadata.txt

**Comment by pavelpereverzev** [comment]
@NyakudyaA hey there! Is everything ok right now?
